[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
async-openai = { version = "0.29.0", features = ["realtime"] }
flows = { version = "0.1.0", path = "../../crates/flows" }
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
